import os

file_path = r'c:\Users\master\Documents\Server\fishing_core\views.py'

# 1. Read the file
with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# 2. Find and replace BattleView
start_bv = -1
end_bv = -1
for i, line in enumerate(lines):
    if 'class BattleView(View):' in line:
        start_bv = i
    if start_bv != -1 and i > start_bv and 'class ' in line:
        end_bv = i
        break

if start_bv != -1:
    if end_bv == -1: end_bv = len(lines)
    
    new_bv = [
        "class BattleView(View):\n",
        "    def __init__(self, user, my_fish, npc_fish):\n",
        "        super().__init__(timeout=120)\n",
        "        self.user = user\n",
        "        self.my_fish = my_fish\n",
        "        self.npc_fish = npc_fish\n",
        "        self.turn = 1\n",
        "        self.ap_gain = 1\n",
        "        self.my_ap = 1\n",
        "        self.npc_ap = 1\n",
        "        self.my_alloc = {'atk': 0, 'blk': 0}\n",
        "        \n",
        "        p1_pwr = FISH_DATA.get(my_fish, {}).get('power', 10)\n",
        "        p2_pwr = FISH_DATA.get(npc_fish, {}).get('power', 10)\n",
        "        self.my_hp = self.my_max_hp = p1_pwr * 12\n",
        "        self.npc_hp = self.npc_max_hp = p2_pwr * 12\n",
        "        self.my_pwr = p1_pwr\n",
        "        self.npc_pwr = p2_pwr\n",
        "        self.battle_log = f'🌊 **{npc_fish}**와(과) 마주쳤습니다!'\n",
        "\n",
        "    def generate_embed(self):\n",
        "        embed = EmbedFactory.build(title=f'⚔️ 전략 수산 배틀 (Turn {self.turn})', type='error')\n",
        "        embed.set_author(name=f'{self.user.name}님의 전투', icon_url=self.user.display_avatar.url)\n",
        "        \n",
        "        def hp_bar(hp, mhp): return create_progress_bar(hp, mhp, length=10)\n",
        "        def ap_bar(ap): return '🟦' * ap + '⬜' * (8 - ap)\n",
        "            \n",
        "        embed.add_field(name=f'🔵 {self.user.name} (나)', value=f'**{self.my_fish}**\\nHP: {hp_bar(self.my_hp, self.my_max_hp)} `{self.my_hp:,}`\\nAP: {ap_bar(self.my_ap)} `({self.my_ap}/8)`', inline=False)\n",
        "        embed.add_field(name='━━━━━ VS ━━━━━', value=f'✨ 다음 턴 AP 수급: `+{self.ap_gain + 1}`', inline=False)\n",
        "        embed.add_field(name='🔴 야생의 적', value=f'**{self.npc_fish}**\\nHP: {hp_bar(self.npc_hp, self.npc_max_hp)} `{self.npc_hp:,}`\\nAP: {ap_bar(self.npc_ap)} `({self.npc_ap}/8)`', inline=False)\n",
        "        \n",
        "        embed.add_field(name='📜 전투 로그', value=f'```md\\n{self.battle_log}```', inline=False)\n",
        "        embed.set_footer(text='💡 팁: 공격 포인트를 모으면 데미지가 기하급수적으로 증가합니다!')\n",
        "        \n",
        "        file = discord.File('assets/battle/battle_start.png', filename='battle_start.png')\n",
        "        embed.set_image(url='attachment://battle_start.png')\n",
        "        return embed, file\n",
        "\n",
        "    async def _update_view(self, interaction):\n",
        "        embed, file = self.generate_embed()\n",
        "        await interaction.edit_original_response(embed=embed, attachments=[file], view=self)\n",
        "\n",
        "    async def _handle_point(self, interaction, type):\n",
        "        if interaction.user != self.user: \n",
        "            return await interaction.response.send_message('❌ 당신의 전투가 아닙니다!', ephemeral=True)\n",
        "        \n",
        "        current_spent = self.my_alloc['atk'] + self.my_alloc['blk']\n",
        "        if current_spent >= self.my_ap: \n",
        "            return await interaction.response.send_message('⚠️ **AP 부족!** 더 이상 포인트를 배분할 수 없습니다.', ephemeral=True)\n",
        "        \n",
        "        self.my_alloc[type] += 1\n",
        "        from fishing_core.services.battle_service import BattleService\n",
        "        mult = BattleService.MULTIPLIERS.get(self.my_alloc['atk'], 0.0)\n",
        "        \n",
        "        # 예쁜 전략 확인 메시지\n",
        "        status_embed = EmbedFactory.build(title='🛡️ 전략 배분 현황', type='info')\n",
        "        status_embed.description = f'현재 {self.user.mention}님이 배분한 포인트입니다.'\n",
        "        status_embed.add_field(name='⚔️ 공격 투자', value=f'`{self.my_alloc[\"atk\"]} pt` (배율: **{mult}x**)', inline=True)\n",
        "        status_embed.add_field(name='🛡️ 방어 투자', value=f'`{self.my_alloc[\"blk\"]} pt`', inline=True)\n",
        "        status_embed.add_field(name='💎 남은 AP', value=f'`{self.my_ap - (self.my_alloc[\"atk\"] + self.my_alloc[\"blk\"])} pt`', inline=True)\n",
        "        \n",
        "        if not interaction.response.is_done():\n",
        "            await interaction.response.send_message(embed=status_embed, ephemeral=True)\n",
        "        else:\n",
        "            await interaction.followup.send(embed=status_embed, ephemeral=True)\n",
        "        await self._update_view(interaction)\n",
        "\n",
        "    @discord.ui.button(label='공격 +1', style=discord.ButtonStyle.danger, emoji='⚔️')\n",
        "    async def btn_atk_plus(self, interaction, button):\n",
        "        await self._handle_point(interaction, 'atk')\n",
        "\n",
        "    @discord.ui.button(label='방어 +1', style=discord.ButtonStyle.primary, emoji='🛡️')\n",
        "    async def btn_blk_plus(self, interaction, button):\n",
        "        await self._handle_point(interaction, 'blk')\n",
        "\n",
        "    @discord.ui.button(label='초기화', style=discord.ButtonStyle.secondary, emoji='🔄')\n",
        "    async def btn_reset(self, interaction, button):\n",
        "        if interaction.user != self.user: return\n",
        "        self.my_alloc = {'atk': 0, 'blk': 0}\n",
        "        await interaction.response.send_message('✅ 배분된 포인트가 초기화되었습니다.', ephemeral=True)\n",
        "        await self._update_view(interaction)\n",
        "\n",
        "    @discord.ui.button(label='전투 개시', style=discord.ButtonStyle.success, emoji='🔥')\n",
        "    async def btn_confirm(self, interaction, button):\n",
        "        if interaction.user != self.user: return\n",
        "        await interaction.response.defer()\n",
        "        \n",
        "        from fishing_core.services.battle_service import BattleService\n",
        "        npc_alloc = {'atk': 0, 'blk': 0}\n",
        "        temp_ap = self.npc_ap\n",
        "        while temp_ap > 0:\n",
        "            choice = random.choice(['atk', 'blk', 'rsv'])\n",
        "            if choice == 'rsv': break\n",
        "            npc_alloc[choice] += 1\n",
        "            temp_ap -= 1\n",
        "            \n",
        "        my_res = BattleService.calculate_ap_battle(self.my_pwr, self.my_alloc['atk'], npc_alloc['blk'])\n",
        "        npc_res = BattleService.calculate_ap_battle(self.npc_pwr, npc_alloc['atk'], self.my_alloc['blk'])\n",
        "        \n",
        "        d1, d2 = my_res['damage'], npc_res['damage']\n",
        "        self.npc_hp -= d1\n",
        "        self.my_hp -= d2\n",
        "        \n",
        "        log = f'[Turn {self.turn} 결과]\\n'\n",
        "        log += f'🔵 나: 공격 {self.my_alloc[\"atk\"]}pt, 방어 {self.my_alloc[\"blk\"]}pt'\n",
        "        log += f' -> {d1:,} 피해!\\n' if d1 > 0 else ' -> 막힘!\\n'\n",
        "        log += f'🔴 적: 공격 {npc_alloc[\"atk\"]}pt, 방어 {npc_alloc[\"blk\"]}pt'\n",
        "        log += f' -> {d2:,} 피해!\\n' if d2 > 0 else ' -> 막힘!\\n'\n",
        "        self.battle_log = log\n",
        "        \n",
        "        if self.npc_hp <= 0: return await self.end_battle(interaction, True)\n",
        "        if self.my_hp <= 0: return await self.end_battle(interaction, False)\n",
        "        \n",
        "        self.my_ap = min(8, (self.my_ap - (self.my_alloc['atk'] + self.my_alloc['blk'])) + self.ap_gain + 1)\n",
        "        self.npc_ap = min(8, (self.npc_ap - (npc_alloc['atk'] + npc_alloc['blk'])) + self.ap_gain + 1)\n",
        "        if self.ap_gain < 3: self.ap_gain += 1\n",
        "        self.turn += 1\n",
        "        self.my_alloc = {'atk': 0, 'blk': 0}\n",
        "        await self._update_view(interaction)\n",
        "\n",
        "    async def end_battle(self, interaction, is_win):\n",
        "        self.stop()\n",
        "        embed = EmbedFactory.build(title='🏆 전투 종료' if is_win else '💀 전투 패배', type='success' if is_win else 'error')\n",
        "        embed.set_author(name=f'{self.user.name}님의 전투 결과', icon_url=self.user.display_avatar.url)\n",
        "        \n",
        "        if is_win:\n",
        "            reward = int(self.npc_pwr * random.randint(5, 10))\n",
        "            await db.execute('UPDATE user_data SET coins = coins + ? WHERE user_id = ?', (reward, self.user.id))\n",
        "            await db.commit()\n",
        "            embed.description = f'치열한 전투 끝에 승리하셨습니다!\\n💰 획득 보상: `{reward:,} C`'\n",
        "            file_name = 'battle_victory.png'\n",
        "        else:\n",
        "            embed.description = '야생의 물고기에게 패배하여 도망쳤습니다...'\n",
        "            file_name = 'battle_defeat.png'\n",
        "            \n",
        "        file = discord.File(f'assets/battle/{file_name}', filename=file_name)\n",
        "        embed.set_image(url=f'attachment://{file_name}')\n",
        "        await interaction.edit_original_response(content=None, embed=embed, attachments=[file], view=None)\n"
    ]
    
    lines = lines[:start_bv] + new_bv + lines[end_bv:]

# 3. Find and replace PvPBattleView
start_pvp = -1
end_pvp = -1
for i, line in enumerate(lines):
    if 'class PvPBattleView(View):' in line:
        start_pvp = i
    if start_pvp != -1 and i > start_pvp and 'class ' in line:
        end_pvp = i
        break

if start_pvp != -1:
    if end_pvp == -1: end_pvp = len(lines)
    
    new_pvp = [
        "class PvPBattleView(View):\n",
        "    def __init__(self, p1, p2, p1_deck, p2_deck):\n",
        "        super().__init__(timeout=300)\n",
        "        self.p1, self.p2 = p1, p2\n",
        "        self.p1_deck, self.p2_deck = p1_deck, p2_deck\n",
        "        self.p1_idx, self.p2_idx = 0, 0\n",
        "        self.turn_count = 1\n",
        "        self.ap_gain = 1\n",
        "        self.p1_ap = self.p2_ap = 1\n",
        "        self.p1_alloc = {'atk': 0, 'blk': 0}\n",
        "        self.p2_alloc = {'atk': 0, 'blk': 0}\n",
        "        self.p1_ready = self.p2_ready = False\n",
        "        self.battle_log = '⚔️ 전략적으로 포인트를 배분하여 승리하세요!'\n",
        "        self._init_fish(1)\n",
        "        self._init_fish(2)\n",
        "\n",
        "    def _init_fish(self, p_num):\n",
        "        if p_num == 1:\n",
        "            name, pwr = self.p1_deck[self.p1_idx]\n",
        "            self.p1_fish, self.p1_pwr = name, pwr\n",
        "            self.p1_hp = self.p1_max_hp = pwr * 12\n",
        "        else:\n",
        "            name, pwr = self.p2_deck[self.p2_idx]\n",
        "            self.p2_fish, self.p2_pwr = name, pwr\n",
        "            self.p2_hp = self.p2_max_hp = pwr * 12\n",
        "\n",
        "    def generate_embed(self, reveal=False):\n",
        "        embed = EmbedFactory.build(title=f'⚔️ 전략 수산대전 (Turn {self.turn_count})', type='warning')\n",
        "        def hp_bar(hp, mhp): return create_progress_bar(hp, mhp, length=10)\n",
        "        def ap_bar(ap): return '🟦' * ap + '⬜' * (8 - ap)\n",
        "\n",
        "        embed.add_field(name=f'🔵 {self.p1.name}', value=f'**{self.p1_fish}**\\nHP: {hp_bar(self.p1_hp, self.p1_max_hp)} `{self.p1_hp:,}`\\nAP: {ap_bar(self.p1_ap)} `({self.p1_ap})`', inline=False)\n",
        "        embed.add_field(name='━━━━━ VS ━━━━━', value=f'✨ 다음 턴 AP 수급: `+{self.ap_gain + 1}`', inline=False)\n",
        "        embed.add_field(name=f'🔴 {self.p2.name}', value=f'**{self.p2_fish}**\\nHP: {hp_bar(self.p2_hp, self.p2_max_hp)} `{self.p2_hp:,}`\\nAP: {ap_bar(self.p2_ap)} `({self.p2_ap})`', inline=False)\n",
        "        \n",
        "        if not reveal:\n",
        "            p1_status = '✅ 준비됨' if self.p1_ready else '🤔 배분 중'\n",
        "            p2_status = '✅ 준비됨' if self.p2_ready else '🤔 배분 중'\n",
        "            embed.add_field(name='🛡️ 전략 준비 상태', value=f'{self.p1.name}: {p1_status} | {self.p2.name}: {p2_status}', inline=False)\n",
        "        \n",
        "        embed.add_field(name='📜 최근 전투 로그', value=f'```md\\n{self.battle_log}```', inline=False)\n",
        "        file = discord.File('assets/battle/battle_start.png', filename='battle_start.png')\n",
        "        embed.set_image(url='attachment://battle_start.png')\n",
        "        return embed, file\n",
        "\n",
        "    async def _update_view(self, interaction):\n",
        "        embed, file = self.generate_embed()\n",
        "        await interaction.edit_original_response(embed=embed, attachments=[file], view=self)\n",
        "\n",
        "    async def _handle_point(self, interaction, type):\n",
        "        is_p1 = (interaction.user == self.p1)\n",
        "        is_p2 = (interaction.user == self.p2)\n",
        "        if not is_p1 and not is_p2: return\n",
        "        \n",
        "        ready = self.p1_ready if is_p1 else self.p2_ready\n",
        "        if ready: return await interaction.response.send_message('❌ 이미 결정을 완료했습니다!', ephemeral=True)\n",
        "        \n",
        "        alloc = self.p1_alloc if is_p1 else self.p2_alloc\n",
        "        ap = self.p1_ap if is_p1 else self.p2_ap\n",
        "        \n",
        "        if alloc['atk'] + alloc['blk'] >= ap: \n",
        "            return await interaction.response.send_message('⚠️ **AP 부족!**', ephemeral=True)\n",
        "        \n",
        "        alloc[type] += 1\n",
        "        from fishing_core.services.battle_service import BattleService\n",
        "        mult = BattleService.MULTIPLIERS.get(alloc['atk'], 0.0)\n",
        "        \n",
        "        status_embed = EmbedFactory.build(title='🛡️ 내 전략 확인', type='info')\n",
        "        status_embed.description = '상대에게는 보이지 않는 나만의 전략 정보입니다.'\n",
        "        status_embed.add_field(name='⚔️ 공격', value=f'`{alloc[\"atk\"]} pt` (배율: **{mult}x**)', inline=True)\n",
        "        status_embed.add_field(name='🛡️ 방어', value=f'`{alloc[\"blk\"]} pt`', inline=True)\n",
        "        status_embed.add_field(name='💎 잔여 AP', value=f'`{ap - (alloc[\"atk\"] + alloc[\"blk\"])} pt`', inline=True)\n",
        "        \n",
        "        if not interaction.response.is_done():\n",
        "            await interaction.response.send_message(embed=status_embed, ephemeral=True)\n",
        "        else:\n",
        "            await interaction.followup.send(embed=status_embed, ephemeral=True)\n",
        "        await self._update_view(interaction)\n",
        "\n",
        "    @discord.ui.button(label='공격+', style=discord.ButtonStyle.danger, emoji='⚔️')\n",
        "    async def btn_atk_plus(self, interaction, button):\n",
        "        await self._handle_point(interaction, 'atk')\n",
        "\n",
        "    @discord.ui.button(label='방어+', style=discord.ButtonStyle.primary, emoji='🛡️')\n",
        "    async def btn_blk_plus(self, interaction, button):\n",
        "        await self._handle_point(interaction, 'blk')\n",
        "\n",
        "    @discord.ui.button(label='초기화', style=discord.ButtonStyle.secondary, emoji='🔄')\n",
        "    async def btn_reset(self, interaction, button):\n",
        "        if interaction.user == self.p1: self.p1_alloc = {'atk': 0, 'blk': 0}\n",
        "        elif interaction.user == self.p2: self.p2_alloc = {'atk': 0, 'blk': 0}\n",
        "        else: return\n",
        "        await interaction.response.send_message('✅ 초기화 완료', ephemeral=True)\n",
        "        await self._update_view(interaction)\n",
        "\n",
        "    @discord.ui.button(label='✅ 결정', style=discord.ButtonStyle.success)\n",
        "    async def btn_confirm(self, interaction, button):\n",
        "        if interaction.user == self.p1: self.p1_ready = True\n",
        "        elif interaction.user == self.p2: self.p2_ready = True\n",
        "        else: return\n",
        "        \n",
        "        if self.p1_ready and self.p2_ready: \n",
        "            await interaction.response.defer()\n",
        "            await self.resolve_turn(interaction)\n",
        "        else: \n",
        "            await interaction.response.send_message('✅ 전략이 확정되었습니다. 상대방의 결정을 기다립니다...', ephemeral=True)\n",
        "            await self._update_view(interaction)\n",
        "\n",
        "    async def resolve_turn(self, interaction):\n",
        "        from fishing_core.services.battle_service import BattleService\n",
        "        p1_res = BattleService.calculate_ap_battle(self.p1_pwr, self.p1_alloc['atk'], self.p2_alloc['blk'])\n",
        "        p2_res = BattleService.calculate_ap_battle(self.p2_pwr, self.p2_alloc['atk'], self.p1_alloc['blk'])\n",
        "        d1, d2 = p1_res['damage'], p2_res['damage']\n",
        "        self.p2_hp -= d1\n",
        "        self.p1_hp -= d2\n",
        "        \n",
        "        log = f'[Turn {self.turn_count} 결과]\\n'\n",
        "        log += f'🔵 {self.p1.name}: 공격 {self.p1_alloc[\"atk\"]}pt / {d1:,} 피해!\\n'\n",
        "        log += f'🔴 {self.p2.name}: 공격 {self.p2_alloc[\"atk\"]}pt / {d2:,} 피해!\\n'\n",
        "        self.battle_log = log\n",
        "        \n",
        "        if self.p1_hp <= 0 or self.p2_hp <= 0:\n",
        "            if self.p1_hp <= 0:\n",
        "                self.p1_idx += 1\n",
        "                if self.p1_idx >= len(self.p1_deck): return await self.end_battle(interaction, self.p2, self.p1)\n",
        "                self._init_fish(1)\n",
        "            if self.p2_hp <= 0:\n",
        "                self.p2_idx += 1\n",
        "                if self.p2_idx >= len(self.p2_deck): return await self.end_battle(interaction, self.p1, self.p2)\n",
        "                self._init_fish(2)\n",
        "\n",
        "        self.p1_ap = min(8, (self.p1_ap - (self.p1_alloc['atk'] + self.p1_alloc['blk'])) + self.ap_gain + 1)\n",
        "        self.p2_ap = min(8, (self.p2_ap - (self.p2_alloc['atk'] + self.p2_alloc['blk'])) + self.ap_gain + 1)\n",
        "        if self.ap_gain < 3: self.ap_gain += 1\n",
        "        self.turn_count += 1\n",
        "        self.p1_ready = self.p2_ready = False\n",
        "        self.p1_alloc = self.p2_alloc = {'atk': 0, 'blk': 0}\n",
        "        \n",
        "        embed, file = self.generate_embed(reveal=True)\n",
        "        await interaction.edit_original_response(embed=embed, attachments=[file], view=self)\n",
        "\n",
        "    async def end_battle(self, interaction, winner, loser):\n",
        "        from fishing_core.database import db\n",
        "        self.stop()\n",
        "        async with db.conn.execute('SELECT coins FROM user_data WHERE user_id=?', (loser.id,)) as cursor:\n",
        "            res = await cursor.fetchone()\n",
        "        loser_coins = res[0] if res else 0\n",
        "        steal = int(loser_coins * random.uniform(0.05, 0.10))\n",
        "        if steal > 0:\n",
        "            await db.execute('UPDATE user_data SET coins = coins - ? WHERE user_id=?', (steal, loser.id))\n",
        "            await db.execute('UPDATE user_data SET coins = coins + ? WHERE user_id=?', (steal, winner.id))\n",
        "            await db.commit()\n",
        "        \n",
        "        embed = EmbedFactory.build(title='⚔️ 대전 종료', type='warning')\n",
        "        embed.description = f'👑 **{winner.name}** 승리!\\n💰 약탈 금액: `{steal:,} C`'\n",
        "        file = discord.File('assets/battle/battle_victory.png', filename='battle_victory.png')\n",
        "        embed.set_image(url='attachment://battle_victory.png')\n",
        "        await interaction.edit_original_response(content=None, embed=embed, attachments=[file], view=None)\n"
    ]
    
    lines = lines[:start_pvp] + new_pvp + lines[end_pvp:]

# 4. Write back
with open(file_path, 'w', encoding='utf-8') as f:
    f.writelines(lines)
print("Success")
