name: Deploy Discord Bot

on:
  push:
    branches:
      - main 
    paths-ignore:
      - '**.json' # 🌟 JSON 파일만 수정될 때는 배포(재시작) 생략!

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GSM SV 서버에 접속해서 배포 대본 실행하기
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 24111
          script: |
            cd /home/ubuntu/discord_bot
            chmod +x deploy.sh
            ./deploy.sh
